name: Sender pipe with receiver

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker ./Sender/*.cpp*   
      
    - name: run for sender
      run: ./testchecker
      
    - name: Build receiver for pipe
      run: gcc -DMAIN -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker1 ./BMS_Receiver/*.c
      
      
    - name: run for receiver
      run: ./testchecker1
    
          
    - name : Sender | Reciever
      run: ./testchecker | ./testchecker1
