name: Sender pipe with receiver

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
          
    - name : Sender | Reciever
      run: ./testsender | ./testreceiver
